### ISSUE TITLE
Support for landscape screen

### ISSUE THREAD

**Issue by dattn-BL** [AgoraIO/FaceUnity#14]
Hi,
Currently the demo application does not support landscape screen. 
I notice this is support in the dev/android branch but there is a lot of changes in this branch include the video-capture-framework-debug.arr file.
Can I get the release version of this file?
Thanks

**Comment by brianxcli** [comment]
Sure, you can go to https://github.com/AgoraIO/Agora-Extensions/tree/master/VideoCapture/Android

**Comment by dattn-BL** [comment]
Thank you!
