### ISSUE TITLE
CameraPreviewSessionListener.onClosed called while the camera state is STARTED

### ISSUE THREAD

**Issue by dattn-BL** [AgoraIO/FaceUnity#15]
On the dev branch, I notice somehow the CameraPreviewSessionListener.onClosed get called while the camera state is STARTED, later, it makes the stopCaptureAndBlockUntilStopped failed due to the mPreviewSession is null, and causes the next startCaptureMaybeAsync call failed as well (due to its status is already STARTED)
I do not have an exact steps but somehow, switch between the Camera app and the demo many times will cause this.
Do you have any idea about this issue?

**Comment by brianxcli** [comment]
Thanks. We've found this issue, and it will be solved soon.

**Comment by brianxcli** [comment]
@dattn-BL you can try if it is solved now.

**Comment by dattn-BL** [comment]
It seems working fine now. 
But is it suppose for the preview session to be released/closed/reset on CameraPreviewSessionListener.onClosed?

**Comment by brianxcli** [comment]
At this moment, just ignore this callback, nothing done here. Maybe it's better to remove this line.

**Comment by dattn-BL** [comment]
I will test more to see if it leads to any issues. Thanks.
