### ISSUE TITLE
ratio is different

### ISSUE THREAD

**Issue by sugitatestblue** [AgoraIO/FaceUnity#45]
resolution ratio is different in video

**Comment by yoreland** [comment]
can you upload a screenshot?

**Comment by sugitatestblue** [comment]
I can't share for confidential
but, narrow height or long width.

`CapturerManager.m` `didOutputVideoFrame` method

I can't know correct ratio but...
```
[newPixelBuffer setParamWithWidth:agmPixelBuffer.width height:agmPixelBuffer.height * 1.1 rotation:agmPixelBuffer.rotation timeStampMs:agmPixelBuffer.timeStampMs];
```

**Comment by sugitatestblue** [comment]
`height * 1.01` or `width * 0.95` ?

**Comment by sugitatestblue** [comment]
I guess `AGMCapturer_iOS`'s bug.

`AGMCapturer_iOS 2.0.0` is bad.

`2.0.1` was fix.
